### PR TITLE
fix backpress issue(#314) raised in Toolkit-Android

### PR DESCRIPTION
**Pull request by tejavojjala**
Made the required changes as discussed in https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/314

### CODE REVIEW

**Comment by iit2014086** [comment]
@opticod seems like the issue is same with Dictation App for the same flow. Update the pr making changes in Dictation and VideoCollection files. Check it now :)

**Comment by opticod** [comment]
@iit2014086, did you well checked your implementation?

**Comment by iit2014086** [comment]
@opticode Yes, I did.

**Comment by opticod** [comment]
@iit2014086, why on clicking video item 3 and then pressing backpress redirects the user to content of video item 2? It should only redirect it to home ? no need of changing the default flow of the app.

**Comment by iit2014086** [comment]
@opticod  okay I first thought of pressing back should work like pressing "Previous button". Then in flash cards template, If user clicks on 1st card, now after that suppose he chooses 5th from navigation drawer, then on clicking back should user go to 1st card or 4th card?

**Comment by opticod** [comment]
It will go to 1st card. The back key will move the user to "back state". Also, restart button, cleans some instances from stack.

**Comment by iit2014086** [comment]
@opticod When a user goes to the last activity(choose a dictation -> Enter Text -> Click Submit) what should happen on clicking back. Currently it goes back to DetailActivity(with text entered). Shouldn't the application close?(Becoz why go back after submitting he should either restart or exit).

**Comment by opticod** [comment]
@iit2014086 , for self correction, he can go back to previous submit fragment. (default flow)

**Comment by opticod** [comment]
@iit2014086, So what is your current implementation?

**Comment by iit2014086** [comment]
@opticod 
In Dictation and Video:
Whenever user presses Restart a new stack of activities is created into which first we push home activity and then detail activity. This way when user presses back he will reach home activity instead of exiting the app. 

In FlashCards:
Instead of finishing the activity whenever user presses next. I am just leaving it in the stack.

**Comment by opticod** [comment]
@tejavojjala , I have merged to dev branch according to recent contribution policy. You can check your merged commit here : https://github.com/BuildmLearn/Toolkit-mobile-templates/commits/dev

**Pull request closed without merging**
